"""Schedule Plug -- core logic.

Turns one still -- a flat image, or a layered Photoshop file -- into a short
animated 16:9 clip with a music bed: the weekly-schedule graphic that used to
need a motion designer for ten seconds of "bring the lines on one by one".

Deliberately has NO Flask and NO imports from the rest of PRISM, like
shorts_core.py: everything takes plain values and returns plain values.

The animation is drawn here, frame by frame, and piped to ffmpeg -- not
generated by a video model. A schedule is text (titles, dates, times) and a
generative model repaints every pixel of every frame, so the one thing the
graphic exists to say would arrive warped. Drawing it means every layer's
pixels are the designer's own, only moved, faded or uncovered, and the last
frame is the artwork exactly.

  1. load_artwork() reads the file into layers, bottom first. A PSD's
     top-level layers become the things that animate; anything else is one
     layer. If the layers can't be put back together to match the file's
     own flattened picture (blend modes, adjustment layers, effects), the
     flattened picture is used as a single layer instead: a plainer
     animation of the right image beats a livelier one of the wrong image.
  2. a recipe says how layers arrive: parse_prompt() reads the editor's
     words directly, and a language model, when one is available, can refine
     that into per-layer choices (parse_recipe_reply()).
  3. build_timeline() spaces the layers out over the opening part of the
     clip, and Animator.frame() draws any moment of it.
  4. encode() pipes the frames to ffmpeg with the music.
"""
import copy
import json
import math
import os
import re
import subprocess

import cv2
import numpy as np


CANVAS = (1920, 1080)
DURATIONS = (10, 15, 20, 30)
IMAGE_EXTENSIONS = {'psd', 'psb', 'png', 'jpg', 'jpeg', 'tif', 'tiff', 'webp', 'bmp'}
MAX_LAYERS = 12             # more than this and the lowest ones are merged into the background
EFFECTS = ('wipe', 'slide', 'fade', 'pop', 'cut')
DIRECTIONS = ('left', 'right', 'up', 'down')
SPEEDS = {'slow': 1.5, 'normal': 1.0, 'fast': 0.6}
STOP_MOTION_FPS = 12.0      # "animated on twos": the stepping that reads as stop motion
PUSH_IN = 0.05              # how much larger the picture is by the last frame of a push-in

# What the layers do once they have arrived, until the end of the plug. The
# background takes no part in any of them.
AMBIENTS = ('none', 'shine', 'float', 'pulse', 'wobble')
AMBIENT_LABELS = {'none': 'hold still', 'shine': 'light sweep', 'float': 'gentle float',
                  'pulse': 'pulse one by one', 'wobble': 'wobble'}
# Animation styles: how the layers arrive + what they do afterwards. The
# prompt, if there is one, changes whatever it names on top of the style.
STYLES = (
    ('fade_shine', 'Fade in + light sweep', {'effect': 'fade', 'direction': 'right', 'ambient': 'shine'}),
    ('wipe_shine', 'Wipe reveal + light sweep', {'effect': 'wipe', 'direction': 'right', 'ambient': 'shine'}),
    ('slide_float', 'Slide up + gentle float', {'effect': 'slide', 'direction': 'up', 'ambient': 'float'}),
    ('pop_pulse', 'Pop in + pulse one by one', {'effect': 'pop', 'direction': 'right', 'ambient': 'pulse'}),
    ('stop_motion', 'Stop motion wipe + wobble', {'effect': 'wipe', 'direction': 'right', 'ambient': 'wobble',
                                                  'stop_motion': True}),
    ('fade_still', 'Fade in + hold still', {'effect': 'fade', 'direction': 'right', 'ambient': 'none'}),
)
DEFAULT_STYLE = 'fade_shine'


class ArtworkError(ValueError):
    """The file could not be turned into something to animate; the message
    is written for the editor who picked it."""


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------

def _premultiply(bgra):
    """Straight-alpha BGRA -> premultiplied. Everything downstream (scaling,
    blending, fading) is done premultiplied, which is what keeps a dark
    fringe from appearing around every edge that gets resampled."""
    out = bgra.copy()
    a = bgra[:, :, 3:4].astype(np.uint16)
    out[:, :, :3] = ((bgra[:, :, :3].astype(np.uint16) * a + 127) // 255).astype(np.uint8)
    return out


def _to_bgra(arr):
    """Any image array cv2 or Pillow hands back -> 8-bit straight BGRA."""
    if arr is None:
        return None
    if arr.dtype == np.uint16:
        arr = (arr / 257.0 + 0.5).astype(np.uint8)
    elif arr.dtype != np.uint8:
        arr = np.clip(arr * (255.0 if arr.max() <= 1.0 else 1.0), 0, 255).astype(np.uint8)
    if arr.ndim == 2:
        arr = cv2.cvtColor(arr, cv2.COLOR_GRAY2BGRA)
    elif arr.shape[2] == 3:
        arr = cv2.cvtColor(arr, cv2.COLOR_BGR2BGRA)
    elif arr.shape[2] == 2:                                   # grey + alpha
        arr = np.dstack([arr[:, :, 0]] * 3 + [arr[:, :, 1]])
    return np.ascontiguousarray(arr[:, :, :4])


def _pil_to_bgra(img):
    return _to_bgra(cv2.cvtColor(np.asarray(img.convert('RGBA')), cv2.COLOR_RGBA2BGRA))


def _crop_to_content(bgra):
    """(cropped, x, y) around the non-transparent pixels, or None if empty."""
    ys, xs = np.where(bgra[:, :, 3] > 0)
    if not len(xs):
        return None
    x0, x1, y0, y1 = int(xs.min()), int(xs.max()) + 1, int(ys.min()), int(ys.max()) + 1
    return np.ascontiguousarray(bgra[y0:y1, x0:x1]), x0, y0


def _fit(size, canvas):
    """Scale and offset that fit `size` inside `canvas` without cropping."""
    k = min(canvas[0] / float(size[0]), canvas[1] / float(size[1]))
    w, h = max(1, int(round(size[0] * k))), max(1, int(round(size[1] * k)))
    return k, (canvas[0] - w) // 2, (canvas[1] - h) // 2


def _place(straight_bgra, x, y, doc_size, canvas):
    """One layer's pixels (straight alpha, at (x, y) in a document of
    `doc_size`) -> a premultiplied crop positioned on the output canvas."""
    k, ox, oy = _fit(doc_size, canvas)
    pm = _premultiply(straight_bgra)
    h, w = pm.shape[:2]
    nw, nh = max(1, int(round(w * k))), max(1, int(round(h * k)))
    if (nw, nh) != (w, h):
        pm = cv2.resize(pm, (nw, nh), interpolation=cv2.INTER_AREA if k < 1 else cv2.INTER_LANCZOS4)
        pm[:, :, :3] = np.minimum(pm[:, :, :3], pm[:, :, 3:4])     # Lanczos can ring past the alpha
    return {'px': np.ascontiguousarray(pm), 'x': ox + int(round(x * k)), 'y': oy + int(round(y * k))}


def _flatten(layers, canvas):
    """All layers composited in order onto black: BGR at canvas size."""
    out = np.zeros((canvas[1], canvas[0], 3), np.uint8)
    for ly in layers:
        paste(out, ly['px'], ly['x'], ly['y'])
    return out


def _merge_backdrop(layers, doc, canvas, notes):
    """Folds every layer that sits directly on the bottom layer and covers
    the whole picture into the bottom layer.

    The bottom layer is the background and does not animate. A texture, a
    gradient or a colour wash laid over all of it is, to the eye, more
    background: left as a layer of its own it would fade in over the
    backdrop half a second into the plug, and the background would be seen
    to change. A layer that only reaches the edges (a border, a frame) does
    not cover the picture and still arrives."""
    k = _fit(doc, canvas)[0]
    area = 0.9 * (doc[0] * k) * (doc[1] * k)

    def covers(ly):
        return int((ly['px'][:, :, 3] > 0).sum()) >= area
    if len(layers) < 2 or not covers(layers[0]):
        return layers
    k = 1
    while k < len(layers) - 1 and covers(layers[k]):    # the top layer is never taken: something must arrive
        k += 1
    if k == 1:
        return layers
    base = np.zeros((canvas[1], canvas[0], 4), np.uint8)
    for ly in layers[:k]:
        paste(base, ly['px'], ly['x'], ly['y'])
    px, x, y = _crop_to_content(base)
    names = ', '.join(f'"{ly["name"]}"' for ly in layers[:k])
    notes.append(f'{names} each cover the whole picture, so together they are the background and stay still. '
                 'The layers above them animate.')
    return [{'px': px, 'x': x, 'y': y, 'name': layers[0]['name']}] + layers[k:]


def _load_flat(path, canvas):
    arr = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if arr is None:
        try:                                    # formats OpenCV's build lacks (some TIFFs, CMYK JPEGs)
            from PIL import Image
            with Image.open(path) as im:
                arr = cv2.cvtColor(np.asarray(im.convert('RGBA')), cv2.COLOR_RGBA2BGRA)
        except Exception as e:
            raise ArtworkError(f'This image could not be read ({e}).') from e
    bgra = _to_bgra(arr)
    h, w = bgra.shape[:2]
    if w < 16 or h < 16:
        raise ArtworkError('This image is too small to use.')
    return [dict(_place(bgra, 0, 0, (w, h), canvas), name='Image')], (w, h)


def _load_psd(path, canvas):
    try:
        from psd_tools import PSDImage
    except ImportError as e:
        raise ArtworkError('Photoshop files need the psd-tools package on the server '
                           '(pip install psd-tools). A PNG or JPEG of the same artwork will work now.') from e
    try:
        psd = PSDImage.open(path)
    except Exception as e:
        raise ArtworkError(f'This Photoshop file could not be opened ({e}).') from e
    doc = (int(psd.width), int(psd.height))
    if doc[0] < 16 or doc[1] < 16:
        raise ArtworkError('This Photoshop file has no usable canvas.')

    notes, layers, plain = [], [], True
    for layer in psd:                                   # bottom first
        if not layer.visible:
            continue
        mode = str(getattr(layer.blend_mode, 'name', layer.blend_mode)).upper()
        if (mode not in ('NORMAL', 'PASS_THROUGH') or layer.kind == 'adjustment'
                or layer.has_effects() or layer.has_clip_layers()):
            plain = False
        img = None
        try:
            # A group is one thing that animates: flattened here. composite()
            # also applies the layer's own mask, which topil() does not.
            img = layer.composite() if (layer.is_group() or layer.has_mask()) else layer.topil()
        except Exception:
            img = None
        if img is None:
            try:
                img = layer.topil()
            except Exception:
                img = None
        if img is None:
            if layer.kind != 'adjustment':
                plain = False                           # a shape or fill with no pixels to read
            continue
        bgra = _pil_to_bgra(img)
        if layer.opacity < 255:
            bgra[:, :, 3] = (bgra[:, :, 3].astype(np.uint16) * int(layer.opacity) // 255).astype(np.uint8)
        cut = _crop_to_content(bgra)
        if cut is None:
            continue
        px, cx, cy = cut
        left, top = layer.bbox[0], layer.bbox[1]
        layers.append(dict(_place(px, left + cx, top + cy, doc, canvas), name=str(layer.name or 'Layer').strip()))

    reference = None
    try:
        ref = psd.topil() if psd.has_preview() else psd.composite()
        if ref is not None:
            reference = _pil_to_bgra(ref)
    except Exception:
        reference = None

    flat_reason = None
    if not layers:
        flat_reason = 'no visible layer in it has pixels PRISM can read'
    elif reference is not None:
        ref_layer = _place(reference, 0, 0, doc, canvas)
        want = np.zeros((canvas[1], canvas[0], 3), np.uint8)
        paste(want, ref_layer['px'], ref_layer['x'], ref_layer['y'])
        diff = float(np.abs(_flatten(layers, canvas).astype(np.int16) - want.astype(np.int16)).mean())
        if diff > 2.5:
            flat_reason = ('its layers use blend modes, effects, masks or adjustment layers that cannot be '
                           'animated one at a time without changing how the artwork looks')
    elif not plain:
        flat_reason = ('its layers use blend modes or effects and the file was saved without a flattened '
                       'preview to check the result against')
    if flat_reason:
        if reference is None:
            raise ArtworkError(f'This Photoshop file cannot be used as it is: {flat_reason}. Save it with '
                               '"Maximize Compatibility" on, or export a PNG.')
        notes.append(f'This Photoshop file was animated as one flat picture, because {flat_reason}. '
                     'For layer-by-layer animation, rasterise or merge those layers so each top-level layer '
                     'is plain pixels in Normal mode.')
        return [dict(_place(reference, 0, 0, doc, canvas), name='Image')], doc, notes

    layers = _merge_backdrop(layers, doc, canvas, notes)
    if len(layers) > MAX_LAYERS:
        # The lowest layers are the backdrop; merging them costs the least.
        keep = MAX_LAYERS - 1
        base = np.zeros((canvas[1], canvas[0], 4), np.uint8)
        for ly in layers[:len(layers) - keep]:
            paste(base, ly['px'], ly['x'], ly['y'])
        merged = _crop_to_content(base)
        notes.append(f'This file has {len(layers)} top-level layers; the lowest {len(layers) - keep} were merged '
                     f'into the background and the top {keep} animate. Group layers in Photoshop to choose '
                     'what moves together.')
        layers = ([{'px': merged[0], 'x': merged[1], 'y': merged[2], 'name': 'Background'}] if merged else []) \
            + layers[len(layers) - keep:]
    return layers, doc, notes


def load_artwork(path, canvas=CANVAS):
    """Reads `path` into {'layers': [...], 'size': (w, h) of the source,
    'layered': bool, 'notes': [str]}.

    Each layer is {'name', 'px': premultiplied BGRA crop, 'x', 'y'} already
    scaled and positioned for `canvas`, bottom layer first. The artwork is
    fitted inside the canvas whole (never cropped: the edge of a schedule is
    usually where the times are), on black."""
    ext = os.path.splitext(path)[1].lower().lstrip('.')
    notes = []
    if ext in ('psd', 'psb'):
        layers, size, notes = _load_psd(path, canvas)
    else:
        layers, size = _load_flat(path, canvas)
    if abs(size[0] / float(size[1]) - canvas[0] / float(canvas[1])) > 0.02:
        notes.append(f'The artwork is {size[0]}x{size[1]}, not 16:9, so it is shown whole with black at the '
                     'sides or top and bottom.')
    if size[0] < canvas[0] * 0.75:
        notes.append(f'The artwork is only {size[0]} pixels wide and was enlarged to {canvas[0]}; text may '
                     'look soft. Use artwork at 1920x1080 or larger.')
    return {'layers': layers, 'size': size, 'layered': len(layers) > 1, 'notes': notes}


# --------------------------------------------------------------------------
# From the editor's words to a recipe
# --------------------------------------------------------------------------

def default_recipe():
    """'background' is the bottom layer of layered artwork and is 'static'
    unless the editor says otherwise: on screen, complete, from the first
    frame, with the other layers arriving over it. A plug is a schedule
    appearing on its backdrop, not a backdrop appearing. 'default' is how
    every other layer arrives -- and how a flat picture does, which has no
    backdrop to stand on and so is itself the thing that arrives."""
    return {'stop_motion': False, 'push_in': False, 'speed': 'normal', 'ambient': 'none',
            'background': {'effect': 'static', 'direction': 'right'},
            'default': {'effect': 'fade', 'direction': 'right'},
            'layers': {}}


def style_recipe(key):
    """The recipe one of STYLES stands for (the default style for a key
    that isn't one)."""
    by_key = {k: v for k, _, v in STYLES}
    v = by_key.get(key) or by_key[DEFAULT_STYLE]
    r = default_recipe()
    r['default'] = {'effect': v['effect'], 'direction': v['direction']}
    r['ambient'] = v['ambient']
    r['stop_motion'] = bool(v.get('stop_motion'))
    return r


def style_label(key):
    return next((label for k, label, _ in STYLES if k == key), None)


def fit_to_artwork(recipe, layer_names):
    """(recipe, note or None): the recipe as this artwork can carry it out.

    Floating, pulsing and wobbling move layers over a background that stays
    put. A flat picture has no layers to move and its background is part of
    it, so those would shake the whole frame; it holds still instead. A light
    sweep moves nothing, so it works on anything."""
    if len(layer_names) > 1 or recipe.get('ambient', 'none') in ('none', 'shine'):
        return recipe, None
    was = AMBIENT_LABELS[recipe['ambient']]
    return dict(recipe, ambient='none'), (
        f'This artwork is one flat picture, so the "{was}" part of the style was left out: it moves layers '
        'over a still background, and a flat picture has no separate layers. It holds still once it has '
        'arrived. A light-sweep style works on flat pictures; for the rest, use a layered Photoshop file.')


_AMBIENT_WORDS = (
    ('none', r'\bhold(s|ing)?\s+still\b|\bstay(s|ing)?\s+still\b|\bthen\s+(hold|freeze)s?\b|\bno\s+loop(ing)?\b'),
    ('shine', r'\blight\s+sweeps?\b|\bshin(e|es|ing|y)\b|\bshimmer\w*|\bglint\w*|\bsheen\b|\bgloss\w*|\bglimmer\w*'),
    # "float the rest up" is a way of arriving; "then everything floats" is what it does afterwards.
    ('float', r'\bfloat(s|ing)?\b(?!\s+(\w+\s+){0,3}(up|in|into|on|down)\b)|\bhover(s|ing)?\b|\bbob(s|bing)?\b'),
    ('pulse', r'\bpuls(e|es|ing)\b|\bbreath(e|es|ing)\b|\bthrob\w*|\bheartbeat\b'),
    ('wobble', r'\bwobbl\w*|\bjitter\w*|\bwiggl\w*|\bshak(e|es|ing|y)\b'),
)


_EFFECT_WORDS = (
    ('wipe', r'\bwip(e|es|ed|ing)\b|\breveal'),
    ('slide', r'\bslid(e|es|ing)\b|\bfl(y|ies|ying)\s+in\b|\bmov(e|es|ing)\s+in\b|\bswe(ep|eps|pt)\b'
              r'|\bfloat(s|ing)?\s+(\w+\s+){0,3}(up|in|into|on|down)\b'),
    ('pop', r'\bpop(s|ped|ping)?\b|\bbounc(e|es|ing)\b|\bscal(e|es|ing)\s+(in|up)\b|\bpunch'),
    ('fade', r'\bfad(e|es|ing)\b|\bdissolv'),
    ('cut', r'\bcut(s)?\s+in\b|\bsnap(s)?\s+(in|on)\b|\bhard\s+cut\b'),
)
# Direction is the way things TRAVEL: a wipe "from the left" moves right.
_DIRECTION_WORDS = (
    ('right', r'left\s+to\s+right|from\s+(the\s+)?left|rightwards?|to\s+the\s+right'),
    ('left', r'right\s+to\s+left|from\s+(the\s+)?right|leftwards?|to\s+the\s+left'),
    ('down', r'top\s+to\s+bottom|from\s+(the\s+)?(top|above)|downwards?|\bdown\b'),
    ('up', r'bottom\s+to\s+top|from\s+(the\s+)?(bottom|below)|upwards?|\bup\b'),
)


def _clause_choice(clause):
    """(effect or None, direction or None) named in one clause of a prompt."""
    effect = next((name for name, pat in _EFFECT_WORDS if re.search(pat, clause)), None)
    direction = next((name for name, pat in _DIRECTION_WORDS if re.search(pat, clause)), None)
    return effect, direction


def parse_prompt(prompt, layer_names=(), base=None):
    """A recipe read straight from the editor's words, with no model.

    Starts from `base` (the chosen style's recipe; the plain default without
    one) and changes only what the words name. Understands the vocabulary
    the animator has and nothing else: which effect (wipe, slide, fade, pop,
    cut), which way, how fast, the two looks that apply to the whole clip
    (stop motion, a slow push in) and what the layers do once they are in
    (light sweep, float, pulse, wobble, hold still). A clause that names a
    layer applies to that layer; one that doesn't sets the default for all
    of them. Anything it doesn't recognise is ignored -- this is the floor
    the result never drops below, not the ceiling.

    The background stays static unless a clause is about the background by
    name ("fade in the background"): "wipe everything in" means everything
    that arrives, and the backdrop does not arrive."""
    r = copy.deepcopy(base) if base else default_recipe()
    text = ' '.join(str(prompt or '').lower().split())
    if not text:
        return r
    for name, pat in _AMBIENT_WORDS:
        if re.search(pat, text):
            r['ambient'] = name
            break
    # Those words are spoken for: "light sweep" is not also a slide.
    for _, pat in _AMBIENT_WORDS:
        text = re.sub(pat, ' ', text)
    if re.search(r'stop[\s-]?motion|stopmotion|claymation|frame[\s-]by[\s-]frame|choppy|jerky', text):
        r['stop_motion'] = True
    if re.search(r'push[\s-]?in|zoom(s|ing)?\s*(in|slowly)?\b|ken\s+burns|slow\s+zoom|drift', text):
        r['push_in'] = True
    # "slow push in" describes the push, not how quickly the layers arrive.
    pace = re.sub(r'\b(slow(ly)?|gentle|gently)\s+(push|zoom|drift)\w*(\s+in)?', ' ', text)
    if re.search(r'\b(fast|quick(ly)?|snappy|rapid|energetic|punchy)\b', pace):
        r['speed'] = 'fast'
    elif re.search(r'\b(slow(ly)?|gentle|gently|calm|elegant|smooth(ly)?)\b', pace):
        r['speed'] = 'slow'

    named = [(n, re.sub(r'[^a-z0-9]+', ' ', n.lower()).strip()) for n in layer_names]
    general = None
    for clause in re.split(r'[.;,\n]|\band\b|\bthen\b|\bwhile\b', text):
        effect, direction = _clause_choice(clause)
        if not effect and not direction:
            continue
        plain = re.sub(r'[^a-z0-9]+', ' ', clause)
        hit = [orig for orig, low in named
               if len(low) >= 3 and (re.search(r'\b' + re.escape(low) + r'\b', plain)
                                     or any(len(w) >= 4 and re.search(r'\b' + re.escape(w) + r's?\b', plain)
                                            for w in low.split()))]
        # A direction on its own turns the style's effect that way round.
        choice = {'effect': effect or r['default']['effect'],
                  'direction': direction or ('right' if effect else r['default']['direction'])}
        if hit and 'background' not in plain:
            for name in hit:
                r['layers'][name.lower()] = dict(choice)
        elif 'background' in plain and (effect or direction):
            r['background'] = dict(choice)
        elif general is None:
            general = choice
    if general:
        r['default'] = general
    return r


def recipe_prompt(prompt, layer_names, base=None):
    """The instruction for a language model: the editor's words in, a recipe
    in this module's vocabulary out. `base` is what is already decided (the
    chosen style, as read so far); the model is shown it and asked to change
    only what the brief calls for."""
    names = '\n'.join(f'- {n}' for n in layer_names) or '- Image'
    b = base or default_recipe()
    now = json.dumps({'stop_motion': b['stop_motion'], 'push_in': b['push_in'], 'speed': b['speed'],
                      'ambient': b.get('ambient', 'none'), 'default': b['default'],
                      'layers': [dict(v, name=k) for k, v in b['layers'].items()]})
    return (
        'You turn a motion designer\'s brief into settings for a simple layer animator. '
        'A still graphic (a TV schedule) is built up on screen layer by layer, bottom layer first, '
        'then stays until the end. The bottom layer is the background: it is on screen from the first '
        'frame and is not yours to animate.\n\n'
        f'The layers, bottom first:\n{names}\n\n'
        'Each layer can arrive with one effect:\n'
        '- "wipe": uncovered progressively, as if a card slid off it\n'
        '- "slide": moves into place from a short distance while fading in\n'
        '- "fade": fades in\n'
        '- "pop": scales up into place with a slight overshoot\n'
        '- "cut": appears instantly\n'
        'and a direction of travel: "right", "left", "up" or "down" (a wipe "from the left" travels "right").\n\n'
        'Settings for the whole clip:\n'
        '- "stop_motion": true for a stepped, hand-made, frame-by-frame look\n'
        '- "push_in": true for a slow continuous zoom toward the picture\n'
        '- "speed": "slow", "normal" or "fast"\n'
        '- "ambient": what the layers do once they have arrived, until the end: "shine" (a light sweeps '
        'across them), "float" (they drift gently up and down), "pulse" (each in turn swells slightly), '
        '"wobble" (a hand-made tremble) or "none" (they hold still)\n\n'
        f'The settings so far:\n{now}\n\n'
        'Reply with JSON only, in exactly that shape, with "layers" as a list of '
        '{"name": "<a layer name from the list>", "effect": "wipe", "direction": "right"}. '
        'Keep every setting the brief does not ask to change.\n'
        '"default" is for every layer above the background that you do not list. List a layer '
        'under "layers" only when the brief treats it differently from the rest. Use only the words given '
        'above; if the brief asks for something this animator cannot do, choose the closest of them.\n\n'
        f'THE BRIEF\n{" ".join(str(prompt or "").split())[:600]}'
    )


def _choice(obj, fallback):
    if not isinstance(obj, dict):
        return dict(fallback)
    effect = str(obj.get('effect') or '').strip().lower()
    direction = str(obj.get('direction') or '').strip().lower()
    return {'effect': effect if effect in EFFECTS else fallback['effect'],
            'direction': direction if direction in DIRECTIONS else fallback['direction']}


def parse_recipe_reply(text, layer_names, base=None):
    """A model's reply -> a valid recipe, or None if nothing usable is in it.

    `base` (usually parse_prompt's reading of the same words) fills whatever
    the reply leaves out or gets wrong, so a half-good reply improves the
    result and a bad one cannot make it worse. Layer names are matched to
    the real ones; a name that isn't a layer is dropped, not guessed at."""
    base = base or default_recipe()
    m = re.search(r'\{.*\}', str(text or ''), re.S)
    if not m:
        return None
    try:
        obj = json.loads(m.group(0))
    except ValueError:
        return None
    if not isinstance(obj, dict) or not any(k in obj for k in ('stop_motion', 'push_in', 'speed', 'background',
                                                                'ambient', 'default', 'layers')):
        return None
    r = {'stop_motion': bool(obj.get('stop_motion', base['stop_motion'])),
         'push_in': bool(obj.get('push_in', base['push_in'])),
         'speed': obj.get('speed') if obj.get('speed') in SPEEDS else base['speed'],
         'ambient': obj.get('ambient') if obj.get('ambient') in AMBIENTS else base.get('ambient', 'none'),
         # Not the model's to decide: static unless the editor's own words
         # were about the background (which parse_prompt has already read).
         'background': dict(base['background']),
         'default': _choice(obj.get('default'), base['default']),
         'layers': dict(base['layers'])}
    real = {n.lower(): n for n in layer_names[1:]}
    rows = obj.get('layers')
    if isinstance(rows, dict):
        rows = [dict(v, name=k) for k, v in rows.items() if isinstance(v, dict)]
    for row in rows if isinstance(rows, list) else []:
        if isinstance(row, dict) and str(row.get('name') or '').strip().lower() in real:
            r['layers'][str(row['name']).strip().lower()] = _choice(row, r['default'])
    return r


def describe_recipe(recipe, layer_names):
    """One line saying what was understood, for the editor to check against
    what they meant."""
    def say(c):
        return c['effect'] if c['effect'] in ('fade', 'pop', 'cut', 'static') else f"{c['effect']} {c['direction']}"
    bits = []
    if len(layer_names) > 1:
        bits.append(f"background: {say(recipe['background'])}")
        special = [f"{n}: {say(recipe['layers'][n.lower()])}" for n in layer_names[1:] if n.lower() in recipe['layers']]
        rest = len(layer_names) - 1 - len(special)
        if rest:
            bits.append(f"{rest} layer{'s' if rest != 1 else ''}: {say(recipe['default'])}")
        bits.extend(special)
    else:
        bits.append(f"picture: {say(recipe['default'])}")
    if recipe['stop_motion']:
        bits.append('stop motion')
    if recipe['push_in']:
        bits.append('slow push in')
    if recipe['speed'] != 'normal':
        bits.append(recipe['speed'])
    if recipe.get('ambient', 'none') != 'none':
        bits.append(f"then {AMBIENT_LABELS[recipe['ambient']]}")
    return '; '.join(bits)


# --------------------------------------------------------------------------
# Timing
# --------------------------------------------------------------------------

def build_timeline(recipe, layer_names, duration):
    """[{'effect', 'direction', 'start', 'dur'}] per layer, bottom first.

    The background of layered artwork is there from the first frame (unless
    the recipe animates it); the rest follow one after another in stacking
    order and are all in place within the opening part of the clip (never
    more than about 45% of it, or six seconds), which then holds: a schedule
    has to be on screen, complete, long enough to be read. A flat picture
    has nothing to stand on, so it arrives itself, from black."""
    n = len(layer_names)
    k = SPEEDS.get(recipe.get('speed'), 1.0)
    lead = 0.25
    if n <= 1:
        return [dict(recipe['default'], start=lead, dur=min(max(0.8, 1.6 * k), duration * 0.4))]
    if recipe['background']['effect'] == 'static':
        # 'cut' at time zero with no duration: drawn in full on frame 0.
        bg = {'effect': 'cut', 'direction': recipe['background']['direction'], 'start': 0.0, 'dur': 0.0}
    else:
        bg = dict(recipe['background'], start=lead, dur=min(1.0, max(0.4, 0.7 * k)))
    rest = n - 1
    window = min(duration * 0.45, 6.0, max(1.2, rest * 0.9)) * k
    window = min(window, duration * 0.6)
    each = float(np.clip(window / rest * 1.6, 0.35, 1.2 * max(k, 1.0)))
    gap = (window - each) / (rest - 1) if rest > 1 else 0.0
    # A beat on the bare background before anything lands on it.
    first = max(0.4, bg['start'] + bg['dur'] * 0.6)
    out = [bg]
    for i, name in enumerate(layer_names[1:]):
        c = recipe['layers'].get(name.lower(), recipe['default'])
        out.append(dict(c, start=first + i * max(gap, 0.0), dur=each))
    return out


def settle_time(timeline):
    """When the last layer has finished arriving."""
    return max(t['start'] + t['dur'] for t in timeline)


# --------------------------------------------------------------------------
# Drawing
# --------------------------------------------------------------------------

def paste(dst, px, x, y, opacity=1.0):
    """Composites a premultiplied BGRA crop onto `dst` (BGR or premultiplied
    BGRA) at (x, y), clipped to it. In place."""
    dh, dw = dst.shape[:2]
    h, w = px.shape[:2]
    x0, y0, x1, y1 = max(0, x), max(0, y), min(dw, x + w), min(dh, y + h)
    if x1 <= x0 or y1 <= y0 or opacity <= 0:
        return
    src = px[y0 - y:y1 - y, x0 - x:x1 - x]
    if opacity < 1.0:
        src = (src.astype(np.float32) * float(opacity) + 0.5).astype(np.uint8)
    inv = 255 - src[:, :, 3:4].astype(np.uint16)
    region = dst[y0:y1, x0:x1]
    c = region.shape[2]
    region[:] = (src[:, :, :c].astype(np.uint16) + (region.astype(np.uint16) * inv + 127) // 255).clip(0, 255).astype(np.uint8)


def ease_out(u):
    u = min(1.0, max(0.0, u))
    return 1.0 - (1.0 - u) ** 3


def ease_out_back(u):
    u = min(1.0, max(0.0, u))
    c1 = 1.70158
    return 1.0 + (c1 + 1.0) * (u - 1.0) ** 3 + c1 * (u - 1.0) ** 2


def _wipe(px, u, direction):
    """The crop with everything past the wipe's edge made transparent. The
    edge is soft (a few percent of the layer) and travels across the LAYER,
    not the frame, so a small caption wipes on in the same time as a full
    width bar instead of popping on as a frame-wide wipe happens to pass."""
    h, w = px.shape[:2]
    horizontal = direction in ('left', 'right')
    n = w if horizontal else h
    soft = max(6.0, 0.08 * n)
    pos = np.arange(n, dtype=np.float32)
    if direction in ('left', 'up'):
        pos = (n - 1) - pos
    ramp = np.clip((u * (n + soft) - pos) / soft, 0.0, 1.0)
    mask = ramp[None, :, None] if horizontal else ramp[:, None, None]
    return (px.astype(np.float32) * mask + 0.5).astype(np.uint8)


def _jitter(layer_index, step):
    """A couple of pixels of repeatable wobble for one layer on one stepped
    frame -- the registration error of an object moved by hand between
    exposures."""
    rng = np.random.default_rng(1000003 * (layer_index + 1) + int(step))
    return int(rng.integers(-3, 4)), int(rng.integers(-2, 3))


def _smooth(x):
    x = min(1.0, max(0.0, x))
    return x * x * (3.0 - 2.0 * x)


def _paste_shifted(dst, px, x, y, dx, dy):
    """paste() at a position that need not be a whole pixel. A slow drift
    in whole pixels is a visible tick every few frames; this is continuous."""
    ix, iy = int(math.floor(dx)), int(math.floor(dy))
    fx, fy = dx - ix, dy - iy
    if fx < 0.02 and fy < 0.02:
        paste(dst, px, x + ix, y + iy)
        return
    h, w = px.shape[:2]
    moved = cv2.warpAffine(px, np.float32([[1, 0, 1 + fx], [0, 1, 1 + fy]]), (w + 2, h + 2),
                           flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=0)
    paste(dst, moved, x + ix - 1, y + iy - 1)


SHINE_EVERY, SHINE_LASTS, SHINE_WIDTH, SHINE_GAIN, SHINE_LEAN = 3.2, 1.2, 90.0, 0.38, 0.4
PULSE_EVERY, PULSE_LASTS, PULSE_GROW = 1.1, 0.9, 0.04
FLOAT_RISE, FLOAT_PERIOD = 4.0, 4.5
EASE_OFF = 0.8              # ongoing motion eases away over the last moments: the final frame is the artwork


class Animator:
    """Draws any moment of the animation: frame(t) -> BGR at canvas size.

    Layers that will not change again are baked into one picture as time
    advances -- every arrived layer when nothing moves afterwards, only the
    background when the layers keep moving -- so a still hold costs a copy
    per frame rather than a full composite. frame() is therefore meant to be
    called with rising t (rewinding works, it just rebuilds).

    Whatever the layers do after arriving, they have stopped doing it by the
    last frame, which is the artwork exactly."""

    def __init__(self, artwork, timeline, recipe, duration, canvas=CANVAS):
        self.layers, self.timeline, self.recipe = artwork['layers'], timeline, recipe
        self.duration, self.canvas = float(duration), canvas
        self.settled_at = settle_time(timeline)
        n = len(self.layers)
        self.ambient = fit_to_artwork(recipe, [None] * n)[0].get('ambient', 'none')
        # Layers from here up keep moving after they arrive; below it, never.
        self._movers = n if self.ambient == 'none' else (1 if n > 1 else 0)
        self._base = np.zeros((canvas[1], canvas[0], 3), np.uint8)
        self._baked = 0
        self._last_t = -1.0

    def _reset(self):
        self._base[:] = 0
        self._baked = 0

    def _draw_arrived(self, dst, i, tm):
        """Layer i, in place, doing whatever the style has it do until the end."""
        ly, tl = self.layers[i], self.timeline[i]
        px, x, y = ly['px'], ly['x'], ly['y']
        w, h = self.canvas
        if self.ambient in ('float', 'wobble'):
            env = _smooth((tm - tl['start'] - tl['dur']) / EASE_OFF) * _smooth((self.duration - tm) / EASE_OFF)
            if self.ambient == 'float':
                # One slow wave running up the stack, each layer a little behind the one below.
                ph = 2.0 * math.pi * tm / FLOAT_PERIOD - 0.7 * i
                _paste_shifted(dst, px, x, y, 1.5 * env * math.sin(0.5 * ph + i), FLOAT_RISE * env * math.sin(ph))
            elif env < 0.5:
                paste(dst, px, x, y)
            else:
                # Held for two steps: the tremble of a hand-placed cel, not a vibration.
                rng = np.random.default_rng(7919 * (i + 1) + int(math.floor(tm * STOP_MOTION_FPS + 1e-6)) // 2)
                paste(dst, px, x + int(rng.integers(-2, 3)), y + int(rng.integers(-1, 2)))
            return
        if self.ambient == 'shine':
            since = tm - (self.settled_at + 0.3)
            k = math.floor(since / SHINE_EVERY) if since >= 0 else -1
            u = (since - k * SHINE_EVERY) / SHINE_LASTS
            ends = self.settled_at + 0.3 + k * SHINE_EVERY + SHINE_LASTS
            if k < 0 or u >= 1.0 or ends > self.duration - 0.15:      # a sweep that could not finish does not start
                paste(dst, px, x, y)
                return
            centre = -0.25 * w + u * 1.5 * w
            reach = 3.0 * SHINE_WIDTH + SHINE_LEAN * h / 2.0
            ph_, pw_ = px.shape[:2]
            c0, c1 = max(0, int(centre - reach) - x), min(pw_, int(centre + reach) + 1 - x)
            if c1 <= c0:
                paste(dst, px, x, y)
                return
            xs = (x + np.arange(c0, c1, dtype=np.float32))[None, :]
            ys = (y + np.arange(ph_, dtype=np.float32))[:, None]
            gain = SHINE_GAIN * np.exp(-(((xs - SHINE_LEAN * (ys - h / 2.0)) - centre) / SHINE_WIDTH) ** 2)
            lit = px.copy()
            part = lit[:, c0:c1].astype(np.float32)
            # Toward white, inside the layer's own shape only (pixels are premultiplied).
            part[:, :, :3] += (part[:, :, 3:4] - part[:, :, :3]) * gain[:, :, None]
            lit[:, c0:c1] = (part + 0.5).astype(np.uint8)
            paste(dst, lit, x, y)
            return
        if self.ambient == 'pulse':
            since = tm - (self.settled_at + 0.4)
            beat = math.floor(since / PULSE_EVERY) if since >= 0 else -1
            u = (since - beat * PULSE_EVERY) / PULSE_LASTS
            ends = self.settled_at + 0.4 + beat * PULSE_EVERY + PULSE_LASTS
            turn = beat % (len(self.layers) - self._movers) + self._movers if beat >= 0 else -1
            if turn != i or u >= 1.0 or ends > self.duration - 0.15:
                paste(dst, px, x, y)
                return
            s = 1.0 + PULSE_GROW * math.sin(math.pi * u) ** 2
            ph_, pw_ = px.shape[:2]
            nw, nh = max(1, int(round(pw_ * s))), max(1, int(round(ph_ * s)))
            paste(dst, cv2.resize(px, (nw, nh), interpolation=cv2.INTER_LINEAR), x + (pw_ - nw) // 2, y + (ph_ - nh) // 2)
            return
        paste(dst, px, x, y)

    def _draw_layer(self, dst, i, t, step, tm):
        ly, tl = self.layers[i], self.timeline[i]
        if t < tl['start']:
            return
        raw = (t - tl['start']) / tl['dur'] if tl['dur'] > 0 else 1.0
        px, x, y = ly['px'], ly['x'], ly['y']
        if raw >= 1.0 or tl['effect'] == 'cut':
            if i >= self._movers:
                self._draw_arrived(dst, i, tm)
            else:
                paste(dst, px, x, y)
            return
        u = ease_out(raw)
        dx = dy = 0
        if self.recipe.get('stop_motion'):
            dx, dy = _jitter(i, step)
        effect, direction = tl['effect'], tl['direction']
        if effect == 'wipe':
            paste(dst, _wipe(px, u, direction), x + dx, y + dy)
        elif effect == 'slide':
            travel = 0.16 * (self.canvas[0] if direction in ('left', 'right') else self.canvas[1])
            off = int(round((1.0 - u) * travel))
            sx = {'right': -off, 'left': off}.get(direction, 0)
            sy = {'down': -off, 'up': off}.get(direction, 0)
            paste(dst, px, x + sx + dx, y + sy + dy, opacity=min(1.0, raw * 2.5))
        elif effect == 'pop':
            s = 0.8 + 0.2 * ease_out_back(raw)
            h, w = px.shape[:2]
            nw, nh = max(1, int(round(w * s))), max(1, int(round(h * s)))
            scaled = cv2.resize(px, (nw, nh), interpolation=cv2.INTER_LINEAR)
            paste(dst, scaled, x + (w - nw) // 2 + dx, y + (h - nh) // 2 + dy, opacity=min(1.0, raw * 3.0))
        else:                                                   # fade
            paste(dst, px, x + dx, y + dy, opacity=u)

    def frame(self, t):
        t = min(max(0.0, float(t)), self.duration)
        stop = bool(self.recipe.get('stop_motion'))
        # Stop motion steps time itself: `ta` for the arrivals, `tm` for
        # whatever the layers go on doing afterwards.
        step = int(math.floor(t * STOP_MOTION_FPS + 1e-6))
        ta = min(step / STOP_MOTION_FPS, t) if stop and t < self.settled_at + 1.0 / STOP_MOTION_FPS else t
        tm = min(step / STOP_MOTION_FPS, t) if stop and t < self.duration else t
        if ta < self._last_t:
            self._reset()
        self._last_t = ta
        while self._baked < self._movers:
            tl = self.timeline[self._baked]
            if ta < tl['start'] + tl['dur'] and not (tl['effect'] == 'cut' and ta >= tl['start']):
                break
            ly = self.layers[self._baked]
            paste(self._base, ly['px'], ly['x'], ly['y'])
            self._baked += 1
        out = self._base.copy()
        for i in range(self._baked, len(self.layers)):
            self._draw_layer(out, i, ta, step, tm)
        if self.recipe.get('push_in'):
            tp = (step / STOP_MOTION_FPS if stop else t) / self.duration
            s = 1.0 + PUSH_IN * min(1.0, max(0.0, tp))
            w, h = self.canvas
            m = np.float32([[s, 0, (1 - s) * w / 2.0], [0, s, (1 - s) * h / 2.0]])
            out = cv2.warpAffine(out, m, (w, h), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)
        return out


# --------------------------------------------------------------------------
# Encoding
# --------------------------------------------------------------------------

def fps_for(fmt_key):
    """(numerator, denominator) the frames are drawn at for a delivery
    format: the format's own rate, so nothing is frame-rate converted (a
    wipe converted from 29.97 to 23.976 judders)."""
    return (24000, 1001) if str(fmt_key or '').endswith('2398') else (30000, 1001)


def build_encode_cmd(ffmpeg, out_path, canvas, fps, duration, music_path=None, music_start=0.0,
                     loudness=-14.0, true_peak=-1.5):
    """ffmpeg command for the master: raw BGR frames on stdin, music (or
    silence) alongside, H.264 at near-lossless quality with PCM audio in a
    .mov -- an intermediate that the delivery formats are then made from.

    The frames are full-range RGB, as images are; the conversion to
    broadcast-range BT.709 is spelled out rather than left to defaults,
    which is the difference between the designer's colours and slightly
    washed-out ones."""
    w, h = canvas
    cmd = [ffmpeg, '-y', '-hide_banner', '-nostats', '-loglevel', 'error',
           '-f', 'rawvideo', '-pix_fmt', 'bgr24', '-s', f'{w}x{h}', '-r', f'{fps[0]}/{fps[1]}', '-i', 'pipe:0']
    if music_path:
        # Looped, so a sting shorter than the plug still covers it; trimmed
        # and faded below, so a track longer than it ends cleanly.
        cmd += ['-stream_loop', '-1', '-ss', f'{max(0.0, float(music_start)):.3f}', '-i', music_path]
        fade = min(1.5, duration / 4.0)
        audio = (f'[1:a:0]atrim=0:{duration:.3f},asetpts=PTS-STARTPTS,aresample=48000,'
                 f'afade=t=in:st=0:d=0.05,afade=t=out:st={duration - fade:.3f}:d={fade:.3f},'
                 f'loudnorm=I={loudness}:TP={true_peak}:LRA=11,aresample=48000[aout]')
    else:
        cmd += ['-f', 'lavfi', '-t', f'{duration:.3f}', '-i', 'anullsrc=channel_layout=stereo:sample_rate=48000']
        audio = '[1:a:0]anull[aout]'
    video = ('[0:v]scale=in_range=pc:out_range=tv:in_color_matrix=bt709:out_color_matrix=bt709:flags=lanczos,'
             'format=yuv420p,setsar=1[vout]')
    cmd += ['-filter_complex', f'{video};{audio}', '-map', '[vout]', '-map', '[aout]',
            '-t', f'{duration:.3f}',
            '-c:v', 'libx264', '-preset', 'medium', '-crf', '12', '-pix_fmt', 'yuv420p', '-profile:v', 'high',
            '-colorspace', 'bt709', '-color_primaries', 'bt709', '-color_trc', 'bt709', '-color_range', 'tv',
            '-c:a', 'pcm_s16le', '-ar', '48000', '-ac', '2', out_path]
    return cmd


class EncodeError(RuntimeError):
    pass


def encode(animator, out_path, fps, duration, ffmpeg='ffmpeg', music_path=None, music_start=0.0,
           loudness=-14.0, true_peak=-1.5, progress=None, timeout=1800):
    """Draws every frame and pipes it to ffmpeg. Returns the frame count.

    `progress(done, total)` is called every few frames; whatever it raises
    (a cancelled job) stops the encode and removes the partial file."""
    total = int(round(duration * fps[0] / float(fps[1])))
    cmd = build_encode_cmd(ffmpeg, out_path, animator.canvas, fps, duration, music_path, music_start,
                           loudness, true_peak)
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    err = b''
    try:
        try:
            for n in range(total):
                proc.stdin.write(animator.frame(n * fps[1] / float(fps[0])).tobytes())
                if progress and (n % 10 == 0 or n == total - 1):
                    progress(n + 1, total)
        except (BrokenPipeError, OSError):
            pass                                    # ffmpeg stopped reading: its own message says why
        try:
            proc.stdin.close()
        except OSError:
            pass
        proc.stdin = None                           # closed by hand; communicate() must not touch it
        try:
            _, err = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired as e:
            raise EncodeError(f'encoding did not finish within {timeout}s') from e
    except BaseException:
        proc.kill()
        proc.wait()
        if os.path.exists(out_path):
            try:
                os.remove(out_path)
            except OSError:
                pass
        raise
    if proc.returncode != 0 or not (os.path.exists(out_path) and os.path.getsize(out_path) > 0):
        if os.path.exists(out_path):
            try:
                os.remove(out_path)
            except OSError:
                pass
        text = ' | '.join(ln.strip() for ln in err.decode('utf-8', 'replace').splitlines() if ln.strip())
        raise EncodeError(text[:600] or f'ffmpeg exited with code {proc.returncode}')
    return total
